# Census Data Import and Cleaning

In [1]:
# Install Census data API
!pip install censusdata

Collecting censusdata
  Downloading CensusData-1.15.post1.tar.gz (26.6 MB)
     |████████████████████████████████| 26.6 MB 16.8 MB/s eta 0:00:01
Requirement already satisfied: pandas in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from censusdata) (1.3.5)
Requirement already satisfied: requests in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from censusdata) (2.27.1)
Requirement already satisfied: pytz>=2017.3 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from pandas->censusdata) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from pandas->censusdata) (1.21.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from pandas->censusdata) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->censusdata) (1.16.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from requests->censusdata) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from requests->censusdata) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from requests->censusdata) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/davidfix/anaconda3/lib/python3.7/site-packages (from requests->censusdata) (2.0.4)
Building wheels for collected packages: censusdata
  Building wheel for censusdata (setup.py) ... done
  Created wheel for censusdata: filename=CensusData-1.15.post1-py3-none-any.whl size=28205763 sha256=81548fd912c58407801eae9077d6ff6a6012ecc3b7171f52e48ad535407c7702
  Stored in directory: /Users/davidfix/Library/Caches/pip/wheels/2f/72/16/5c8e185711751db7fa81da8c6329c8b3d82c0582a51a0f1e85
Successfully built censusdata
Installing collected packages: censusdata
Successfully installed censusdata-1.15.post1

In [2]:
# Import needed packages
import pandas as pd
import censusdata
import numpy as np

In [ ]:
# Get all states Geo codes
# In order to access this data you may have to request a key to be sent to your email address from Key Signup: https://api.census.gov/data/key_signup.html
states = censusdata.geographies(censusdata.censusgeo([('state', '*')]), 'acs5', 2018,key='b15ade4ca040c6435803ef83605eccaa17abb8e0')

#select Michigan
statecode = states['Michigan']
statecode
# states

censusgeo((('state', '26'),))

In [ ]:
# counties = censusdata.geographies(censusdata.censusgeo([('state', '*'),("county","*")]), 'acs5', 2018,key='b15ade4ca040c6435803ef83605eccaa17abb8e0')
# counties

In [ ]:
# Get all school district names and codes in Michigan
schooldistricts = censusdata.geographies(censusdata.censusgeo([('state', '26'), ('school district (unified)', '*')]), 'acs5', 2018,key='b15ade4ca040c6435803ef83605eccaa17abb8e0')

#print sample
list(schooldistricts)[:2]
schooldistricts

{"L'Anse Area Schools, Michigan": censusgeo((('state', '26'), ('school district (unified)', '00018'))),
 'Superior Central Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '00019'))),
 'Adams Township School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '01890'))),
 'Addison Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '01920'))),
 'Adrian City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '01950'))),
 'Airport Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '01980'))),
 'Akron-Fairgrove Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '02010'))),
 'Alba Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '02040'))),
 'Alcona Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '02160'))),
 'Algonac Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '02190'))),
 'North Huron School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '25780'))),
 'North Adams-Jerome Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '25650'))),
 'Martin Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '22980'))),
 'Marysville Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23040'))),
 'Mason Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23070'))),
 'Mason Consolidated Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23100'))),
 'Mason County Central Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23130'))),
 'Mattawan Consolidated School, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23250'))),
 'Mayville Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23280'))),
 'McBain Rural Agricultural Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23310'))),
 'Melvindale-North Allen Park School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23460'))),
 'Memphis Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23490'))),
 'Mendon Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23520'))),
 'Menominee Area Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23550'))),
 'Meridian Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23580'))),
 'Merrill Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23610'))),
 'Mesick Consolidated Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23670'))),
 'Michigan Center School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23790'))),
 'Midland Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23820'))),
 'Mid Peninsula School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23830'))),
 'Milan Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23850'))),
 'Millington Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '23910'))),
 'Mio-AuSable Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24000'))),
 'Mona Shores Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24120'))),
 'Monroe Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24150'))),
 'Montague Area Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24180'))),
 'Montrose Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24420'))),
 'Morenci Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24570'))),
 'Morley Stanwood Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24600'))),
 'Morrice Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24630'))),
 'Mount Clemens Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24690'))),
 'Mount Morris Consolidated School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24720'))),
 'Mount Pleasant City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24750'))),
 'Munising Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24810'))),
 'Muskegon City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24840'))),
 'Muskegon Heights School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24870'))),
 'Napoleon Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '24960'))),
 'Elkton-Pigeon-Bay Port Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '13090'))),
 'Bentley Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '04800'))),
 'Benton Harbor Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '04830'))),
 'Benzie County Central School, Michigan': censusgeo((('state', '26'), ('school district (unified)', '04950'))),
 'Berkley School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '05010'))),
 'Berrien Springs Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '05430'))),
 'Big Bay de Noc School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '05690'))),
 'Big Rapids Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '05780'))),
 'Birch Run Area School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '05820'))),
 'Birmingham City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '05850'))),
 'Blissfield Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06000'))),
 'Bloomfield Hills School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06090'))),
 'Bloomingdale Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06270'))),
 'Boyne City Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06500'))),
 'Boyne Falls Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06510'))),
 'Brandon School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06570'))),
 'Breckenridge Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06630'))),
 'Breitung Township Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06720'))),
 'Bridgeport-Spaulding Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '06780'))),
 'Remainder of Michigan, Michigan': censusgeo((('state', '26'), ('school district (unified)', '99999'))),
 'East Jordan Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12560'))),
 'East Detroit Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12450'))),
 'East Grand Rapids Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12480'))),
 'East Jackson Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12540'))),
 'East Lansing School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12600'))),
 'Eaton Rapids Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12690'))),
 'Eau Claire Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12810'))),
 'Ecorse Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12930'))),
 'Linden Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '21690'))),
 'Leslie Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '21450'))),
 'Hazel Park City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18030'))),
 'Hemlock Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18180'))),
 'Hesperia Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18270'))),
 'Highland Park City Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18330'))),
 'Hillman Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18360'))),
 'Hillsdale Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18390'))),
 'Holland City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18420'))),
 'Holly Area School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18450'))),
 'Holt Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18480'))),
 'Holton Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18510'))),
 'Homer Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18540'))),
 'Hopkins Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18570'))),
 'Houghton Lake Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18600'))),
 'Howell Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18720'))),
 'Hudson Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18810'))),
 'Hudsonville Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18840'))),
 'Huron School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18930'))),
 'Huron Valley Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '18990'))),
 'Ida Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19050'))),
 'Imlay City Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19100'))),
 'Inland Lakes Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19170'))),
 'Ionia Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19250'))),
 'Iron Mountain Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19410'))),
 'Reading Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29400'))),
 'Redford Union School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29460'))),
 'Reed City Area Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29490'))),
 'Reese Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29520'))),
 'Kenowa Hills Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '20280'))),
 'Kalkaska Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '20050'))),
 'Kearsley Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '20070'))),
 'Central Lake Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08610'))),
 'Central Montcalm Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08640'))),
 'Centreville Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08670'))),
 'Charlevoix Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08730'))),
 'Charlotte Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08770'))),
 'Chassell Township School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08880'))),
 'Cheboygan Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08910'))),
 'Chelsea School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '08940'))),
 'Chesaning Union Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '09150'))),
 'Chippewa Hills School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '09560'))),
 'Chippewa Valley Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '09570'))),
 'Clare Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '09750'))),
 'Clarenceville School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '09840'))),
 'Clarkston Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '09900'))),
 'Clawson City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '09930'))),
 'Climax-Scotts Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '10020'))),
 'Clinton Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '10050'))),
 'Clintondale Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '10080'))),
 'Clio Area School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '10110'))),
 'Colon Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '10410'))),
 'Coldwater Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '10140'))),
 'Decatur Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '11670'))),
 'Deckerville Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '11700'))),
 'Delton-Kellogg School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '11910'))),
 'DeTour Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '11970'))),
 'Detroit City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12000'))),
 'Dexter Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12030'))),
 'Dowagiac Union Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12150'))),
 'Dryden Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12240'))),
 'Dundee Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12300'))),
 'Durand Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12330'))),
 'East China School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '12420'))),
 'Wayland Union Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35550'))),
 'Watersmeet Township School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35340'))),
 'Watervliet School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35460'))),
 'Waverly Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35520'))),
 'Webberville Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35730'))),
 'West Bloomfield School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35820'))),
 'West Branch-Rose City Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35850'))),
 'West Ottawa Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35910'))),
 'Reeths-Puffer Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29540'))),
 'Republic-Michigamme Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29580'))),
 'Richmond Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29670'))),
 'River Rouge School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29760'))),
 'River Valley School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29790'))),
 'Riverview Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29910'))),
 'Rochester Community School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '29940'))),
 'Rockford Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '30030'))),
 'Rogers City Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '30060'))),
 'Western School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35940'))),
 'Westwood Heights Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '35970'))),
 'White Cloud Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36060'))),
 'White Pigeon Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36120'))),
 'Whitefish Township Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36240'))),
 'Whiteford Agricultural School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36270'))),
 'Whitehall School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36300'))),
 'Whitmore Lake Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36330'))),
 'Whittemore-Prescott Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36390'))),
 'Williamston Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36420'))),
 'Wolverine Community Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36480'))),
 'Woodhaven-Brownstown School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36485'))),
 'Wyandotte City School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36540'))),
 'Wyoming Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36570'))),
 'Yale Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '36600'))),
 'North Branch Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '25680'))),
 'Grosse Pointe Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '25740'))),
 'Ironwood Area Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19470'))),
 'Ishpeming Public School District, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19530'))),
 'Ithaca Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19580'))),
 'Jackson Public Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19620'))),
 'Jefferson Schools, Michigan': censusgeo((('state', '26'), ('school district (unified)', '19800'))),

In [ ]:
# Get list of school districts geography codes
sd_nums = []
for schooldistrict in schooldistricts:
  sd_nums.append(schooldistricts[schooldistrict].params()[1][1])

In [ ]:
# Print 5 sample district codes and length of codes
print(sd_nums[:5]) #print sample
len(sd_nums) #516 school districts

['00018', '00019', '01890', '01920', '01950']

516

In [ ]:
df = pd.DataFrame(dict(censusdata.censustable('acs5', 2018, 'B14001'))).T.reset_index()
df.columns

df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
example_of_returned_data = censusdata.download('acs5', 2018, 
            censusdata.censusgeo([('state', '26'),
                                  ('school district (unified)', "00018")]),
                                  # ('block group', '*')]),
            index_list, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')
example_of_returned_data

,B14001_001E,B14001_002E,B14001_003E,B14001_004E,B14001_005E,B14001_006E,B14001_007E,B14001_008E,B14001_009E,B14001_010E
"L'Anse Area Schools, Michigan: Summary level: 970, state:26> school district (unified):00018",4522,1044,60,55,282,195,307,133,12,3478

# Identify table variables

In [ ]:
#download available data elements and Table IDs
#looked through this in Excel

url = 'https://www2.census.gov/programs-surveys/acs/summary_file/2018/documentation/user_tools/ACS2018_Table_Shells.xlsx'
pd.set_option('display.max_rows', 50)
tableids = pd.read_excel(url, header=0)
tableids

,Table ID,Line,UniqueID,Stub,Data Release
0,,NaN,NaN,NaN,NaN
1,B00001,NaN,NaN,UNWEIGHTED SAMPLE COUNT OF THE POPULATION,"1,5"
2,B00001,NaN,NaN,Universe: Total population,NaN
3,B00001,1,B00001_001,Total,NaN
4,NaN,,NaN,NaN,NaN
...,...,...,...,...,...
40027,B99283,1.5,NaN,Allocated:,NaN
40028,B99283,2,B99283_002,Dial-up,NaN
40029,B99283,3,B99283_003,"Broadband such as cable, fiberoptic, or DSL, s...",NaN
40030,B99283,4,B99283_004,Cellular data plan,NaN
40031,B99283,5,B99283_005,Not allocated,NaN

In [ ]:
# search for desired information

searched_tables = tableids[tableids['Stub'].str.contains("EDUCATIONAL ATTAINMENT", na=False)]
searched_tables
# list(searched_tables.Stub)

### First three in list
# SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER
# SEX BY SCHOOL ENROLLMENT BY LEVEL OF SCHOOL BY TYPE OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER
# SCHOOL ENROLLMENT BY LEVEL OF SCHOOL BY TYPE OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER'
# ALLOCATION OF SCHOOL ENROLLMENT FOR THE POPULATION 3 YEARS AND OVER #### Last one 
### Considering both private and public schools?
# SCHOOL ENROLLMENT BY TYPE OF SCHOOL BY AGE FOR THE POPULATION 3 YEARS AND OVER

,Table ID,Line,UniqueID,Stub,Data Release
3190,B06009,,NaN,PLACE OF BIRTH BY EDUCATIONAL ATTAINMENT IN TH...,"1,5"
3223,B06009PR,,NaN,PLACE OF BIRTH BY EDUCATIONAL ATTAINMENT IN PU...,"1,5"
4244,B07009,,NaN,GEOGRAPHICAL MOBILITY IN THE PAST YEAR BY EDUC...,"1,5"
4283,B07009PR,,NaN,GEOGRAPHICAL MOBILITY IN THE PAST YEAR BY EDUC...,"1,5"
5437,B07409,NaN,NaN,GEOGRAPHICAL MOBILITY IN THE PAST YEAR BY EDUC...,"1,5"
5470,B07409PR,NaN,NaN,GEOGRAPHICAL MOBILITY IN THE PAST YEAR BY EDUC...,"1,5"
11120,B13014,NaN,NaN,WOMEN 15 TO 50 YEARS WHO HAD A BIRTH IN THE PA...,"1,5"
11407,B14005,NaN,NaN,SEX BY SCHOOL ENROLLMENT BY EDUCATIONAL ATTAIN...,"1,5"
11439,C14005,NaN,NaN,SEX BY SCHOOL ENROLLMENT BY EDUCATIONAL ATTAIN...,1
11795,B15001,,NaN,SEX BY AGE BY EDUCATIONAL ATTAINMENT FOR THE P...,"1,5"
11881,B15002,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
11919,C15002,NaN,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
11939,B15002A,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
11961,C15002A,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
11975,B15002B,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
11997,C15002B,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12011,B15002C,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
12033,C15002C,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12047,B15002D,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
12069,C15002D,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12083,B15002E,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
12105,C15002E,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12119,B15002F,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
12141,C15002F,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12155,B15002G,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
12177,C15002G,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12191,B15002H,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
12213,C15002H,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12227,B15002I,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,1
12249,C15002I,,NaN,SEX BY EDUCATIONAL ATTAINMENT FOR THE POPULATI...,"1,5"
12263,B15003,NaN,NaN,EDUCATIONAL ATTAINMENT FOR THE POPULATION 25 Y...,"1,5"
12291,C15003,NaN,NaN,EDUCATIONAL ATTAINMENT FOR THE POPULATION 25 Y...,1
13250,B16010,,NaN,EDUCATIONAL ATTAINMENT AND EMPLOYMENT STATUS B...,"1,5"
13306,C16010,NaN,NaN,EDUCATIONAL ATTAINMENT AND EMPLOYMENT STATUS B...,1
14213,B17003,,NaN,POVERTY STATUS IN THE PAST 12 MONTHS OF INDIVI...,"1,5"
14239,C17003,,NaN,POVERTY STATUS IN THE PAST 12 MONTHS OF INDIVI...,1
15471,B17018,,NaN,POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILI...,"1,5"
15509,C17018,,NaN,POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILI...,1
19234,B20004,,NaN,MEDIAN EARNINGS IN THE PAST 12 MONTHS (IN 2018...,"1,5"
20916,B21003,,NaN,VETERAN STATUS BY EDUCATIONAL ATTAINMENT FOR T...,"1,5"
22605,B23006,,NaN,EDUCATIONAL ATTAINMENT BY EMPLOYMENT STATUS FO...,"1,5"
31895,B25013,,NaN,TENURE BY EDUCATIONAL ATTAINMENT OF HOUSEHOLDER,"1,5"
35007,B26106,NaN,NaN,GROUP QUARTERS TYPE (3 TYPES) BY EDUCATIONAL A...,"1,5"
36056,B26206,NaN,NaN,GROUP QUARTERS TYPE (5 TYPES) BY EDUCATIONAL A...,"1,5"
38777,B27019,NaN,NaN,HEALTH INSURANCE COVERAGE STATUS AND TYPE BY A...,"1,5"
39042,B28006,,NaN,EDUCATIONAL ATTAINMENT BY PRESENCE OF A COMPUT...,"1,5"
39210,B29002,,NaN,"CITIZEN, VOTING-AGE POPULATION BY EDUCATIONAL ...","1,5"
39548,B99151,,NaN,ALLOCATION OF EDUCATIONAL ATTAINMENT FOR THE P...,"1,5"

In [ ]:
censusdata.censustable('acs5', 2018, 'B14001')

OrderedDict([('B14001_001E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total',
               'predicateType': 'int'}),
             ('B14001_002E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school',
               'predicateType': 'int'}),
             ('B14001_003E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school!!Enrolled in nursery school, preschool',
               'predicateType': 'int'}),
             ('B14001_004E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school!!Enrolled in kindergarten',
               'predicateType': 'int'}),
             ('B14001_005E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school!!Enrolled in grade 1 to grade 4',
               'predicateType': 'int'}),
             ('B14001_006E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school!!Enrolled in grade 5 to grade 8',
               'predicateType': 'int'}),
             ('B14001_007E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school!!Enrolled in grade 9 to grade 12',
               'predicateType': 'int'}),
             ('B14001_008E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school!!Enrolled in college, undergraduate years',
               'predicateType': 'int'}),
             ('B14001_009E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Enrolled in school!!Graduate or professional school',
               'predicateType': 'int'}),
             ('B14001_010E',
              {'concept': 'SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE POPULATION 3 YEARS AND OVER',
               'label': 'Estimate!!Total!!Not enrolled in school',
               'predicateType': 'int'})])

In [ ]:
pd.DataFrame(dict(censusdata.censustable('acs5', 2018, 'B14001'))).T.reset_index()

,index,label,concept,predicateType
0,B14001_001E,Estimate!!Total,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
1,B14001_002E,Estimate!!Total!!Enrolled in school,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
2,B14001_003E,Estimate!!Total!!Enrolled in school!!Enrolled ...,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
3,B14001_004E,Estimate!!Total!!Enrolled in school!!Enrolled ...,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
4,B14001_005E,Estimate!!Total!!Enrolled in school!!Enrolled ...,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
5,B14001_006E,Estimate!!Total!!Enrolled in school!!Enrolled ...,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
6,B14001_007E,Estimate!!Total!!Enrolled in school!!Enrolled ...,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
7,B14001_008E,Estimate!!Total!!Enrolled in school!!Enrolled ...,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
8,B14001_009E,Estimate!!Total!!Enrolled in school!!Graduate ...,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int
9,B14001_010E,Estimate!!Total!!Not enrolled in school,SCHOOL ENROLLMENT BY LEVEL OF SCHOOL FOR THE P...,int

In [ ]:
#use table name to look up all columns in a table
# use 'Variable name' in query below
# variable_labels = censusdata.printtable(censusdata.censustable('acs5', 2018, 'B14001'))
# pd.DataFrame(variable_labels)
 
## ACS 5 year estimates, year 2018, 3rd parameter is the table ID from the searched tables mentioned above
df = pd.DataFrame(dict(censusdata.censustable('acs5', 2018, 'B14001'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))


df2 = pd.DataFrame(dict(censusdata.censustable('acs5', 2018, 'B25013'))).T.reset_index()
df2['label'] = df2['label'].str.replace("!!",' ')
index_list2 = list(df2["index"])
label_list2 = list(df2["label"])
renamed_columns_dict2= dict(zip(index_list2,label_list2))


df3 = pd.DataFrame(dict(censusdata.censustable('acs5', 2018, 'B15003'))).T.reset_index()
df3['label'] = df3['label'].str.replace("!!",' ')
index_list3 = list(df3["index"])
label_list3 = list(df3["label"])
renamed_columns_dict3= dict(zip(index_list3,label_list3))

renamed_columns_dict3["B15003_001E"] = "Estimated Population over 25"
renamed_columns_dict3

{'B15003_001E': 'Estimated Population over 25',
 'B15003_002E': 'Estimate Total No schooling completed',
 'B15003_003E': 'Estimate Total Nursery school',
 'B15003_004E': 'Estimate Total Kindergarten',
 'B15003_005E': 'Estimate Total 1st grade',
 'B15003_006E': 'Estimate Total 2nd grade',
 'B15003_007E': 'Estimate Total 3rd grade',
 'B15003_008E': 'Estimate Total 4th grade',
 'B15003_009E': 'Estimate Total 5th grade',
 'B15003_010E': 'Estimate Total 6th grade',
 'B15003_011E': 'Estimate Total 7th grade',
 'B15003_012E': 'Estimate Total 8th grade',
 'B15003_013E': 'Estimate Total 9th grade',
 'B15003_014E': 'Estimate Total 10th grade',
 'B15003_015E': 'Estimate Total 11th grade',
 'B15003_016E': 'Estimate Total 12th grade, no diploma',
 'B15003_017E': 'Estimate Total Regular high school diploma',
 'B15003_018E': 'Estimate Total GED or alternative credential',
 'B15003_019E': 'Estimate Total Some college, less than 1 year',
 'B15003_020E': 'Estimate Total Some college, 1 or more years, no degree',
 'B15003_021E': "Estimate Total Associate's degree",
 'B15003_022E': "Estimate Total Bachelor's degree",
 'B15003_023E': "Estimate Total Master's degree",
 'B15003_024E': 'Estimate Total Professional school degree',
 'B15003_025E': 'Estimate Total Doctorate degree'}

In [ ]:
index_list3

['B15003_001E',
 'B15003_002E',
 'B15003_003E',
 'B15003_004E',
 'B15003_005E',
 'B15003_006E',
 'B15003_007E',
 'B15003_008E',
 'B15003_009E',
 'B15003_010E',
 'B15003_011E',
 'B15003_012E',
 'B15003_013E',
 'B15003_014E',
 'B15003_015E',
 'B15003_016E',
 'B15003_017E',
 'B15003_018E',
 'B15003_019E',
 'B15003_020E',
 'B15003_021E',
 'B15003_022E',
 'B15003_023E',
 'B15003_024E',
 'B15003_025E']

In [ ]:
## Total Population
df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B01003'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B01003_001E': 'Estimate Total'}

In [ ]:
## Race
df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B02001'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B02001_001E': 'Estimate Total',
 'B02001_002E': 'Estimate Total White alone',
 'B02001_003E': 'Estimate Total Black or African American alone',
 'B02001_004E': 'Estimate Total American Indian and Alaska Native alone',
 'B02001_005E': 'Estimate Total Asian alone',
 'B02001_006E': 'Estimate Total Native Hawaiian and Other Pacific Islander alone',
 'B02001_007E': 'Estimate Total Some other race alone',
 'B02001_008E': 'Estimate Total Two or more races',
 'B02001_009E': 'Estimate Total Two or more races Two races including Some other race',
 'B02001_010E': 'Estimate Total Two or more races Two races excluding Some other race, and three or more races'}

In [ ]:
## MEDIAN HOUSEHOLD INCOME IN THE PAST 12 MONTHS 
df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B19013'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B19013_001E': 'Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars)'}

In [ ]:
## SCHOOL ENROLLMENT BY DETAILED LEVEL OF SCHOOL FOR THE POPULATION 3 AND OVER 
df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B14001'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B14001_001E': 'Estimate Total',
 'B14001_002E': 'Estimate Total Enrolled in school',
 'B14001_003E': 'Estimate Total Enrolled in school Enrolled in nursery school, preschool',
 'B14001_004E': 'Estimate Total Enrolled in school Enrolled in kindergarten',
 'B14001_005E': 'Estimate Total Enrolled in school Enrolled in grade 1 to grade 4',
 'B14001_006E': 'Estimate Total Enrolled in school Enrolled in grade 5 to grade 8',
 'B14001_007E': 'Estimate Total Enrolled in school Enrolled in grade 9 to grade 12',
 'B14001_008E': 'Estimate Total Enrolled in school Enrolled in college, undergraduate years',
 'B14001_009E': 'Estimate Total Enrolled in school Graduate or professional school',
 'B14001_010E': 'Estimate Total Not enrolled in school'}

In [ ]:
## EDUCATIONAL ATTAINMENT FOR THE POPULATION 25 AND OVER
df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B15003'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B15003_001E': 'Estimate Total',
 'B15003_002E': 'Estimate Total No schooling completed',
 'B15003_003E': 'Estimate Total Nursery school',
 'B15003_004E': 'Estimate Total Kindergarten',
 'B15003_005E': 'Estimate Total 1st grade',
 'B15003_006E': 'Estimate Total 2nd grade',
 'B15003_007E': 'Estimate Total 3rd grade',
 'B15003_008E': 'Estimate Total 4th grade',
 'B15003_009E': 'Estimate Total 5th grade',
 'B15003_010E': 'Estimate Total 6th grade',
 'B15003_011E': 'Estimate Total 7th grade',
 'B15003_012E': 'Estimate Total 8th grade',
 'B15003_013E': 'Estimate Total 9th grade',
 'B15003_014E': 'Estimate Total 10th grade',
 'B15003_015E': 'Estimate Total 11th grade',
 'B15003_016E': 'Estimate Total 12th grade, no diploma',
 'B15003_017E': 'Estimate Total Regular high school diploma',
 'B15003_018E': 'Estimate Total GED or alternative credential',
 'B15003_019E': 'Estimate Total Some college, less than 1 year',
 'B15003_020E': 'Estimate Total Some college, 1 or more years, no degree',
 'B15003_021E': "Estimate Total Associate's degree",
 'B15003_022E': "Estimate Total Bachelor's degree",
 'B15003_023E': "Estimate Total Master's degree",
 'B15003_024E': 'Estimate Total Professional school degree',
 'B15003_025E': 'Estimate Total Doctorate degree'}

In [ ]:
## MEDIAN AGE
df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B01002'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B01002_001E': 'Estimate Median age -- Total',
 'B01002_002E': 'Estimate Median age -- Male',
 'B01002_003E': 'Estimate Median age -- Female'}

In [ ]:
## RECEIPT OF SSI, FOOD STAMPS, ETC

df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B09010'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B09010_001E': 'Estimate Total',
 'B09010_002E': 'Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months',
 'B09010_003E': 'Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households',
 'B09010_004E': 'Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households In married-couple family',
 'B09010_005E': 'Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households In male householder, no wife present, family',
 'B09010_006E': 'Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households In female householder, no husband present, family',
 'B09010_007E': 'Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In nonfamily households',
 'B09010_008E': 'Estimate Total Living in household with no Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months',
 'B09010_009E': 'Estimate Total Living in household with no Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households',
 'B09010_010E': 'Estimate Total Living in household with no Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households In married-couple family',
 'B09010_011E': 'Estimate Total Living in household with no Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households In male householder, no wife present, family',
 'B09010_012E': 'Estimate Total Living in household with no Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In family households In female householder, no husband present, family',
 'B09010_013E': 'Estimate Total Living in household with no Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months In nonfamily households'}

In [ ]:
## HOUSEHOLD TYPE

df = pd.DataFrame(dict(censusdata.censustable('acs1', 2018, 'B11001'))).T.reset_index()
df.columns
df['label'] = df['label'].str.replace("!!",' ')
index_list = list(df["index"])
label_list = list(df["label"])
renamed_columns_dict= dict(zip(index_list,label_list))
renamed_columns_dict

{'B11001_001E': 'Estimate Total',
 'B11001_002E': 'Estimate Total Family households',
 'B11001_003E': 'Estimate Total Family households Married-couple family',
 'B11001_004E': 'Estimate Total Family households Other family',
 'B11001_005E': 'Estimate Total Family households Other family Male householder, no wife present',
 'B11001_006E': 'Estimate Total Family households Other family Female householder, no husband present',
 'B11001_007E': 'Estimate Total Nonfamily households',
 'B11001_008E': 'Estimate Total Nonfamily households Householder living alone',
 'B11001_009E': 'Estimate Total Nonfamily households Householder not living alone'}

In [ ]:
## Take 2
attr = {
        #  'B01003_001E': 'Estimate Total', 
         'B02001_002E': 'Estimate Total White alone',
         'B02001_003E': 'Estimate Total Black or African American alone',
         'B02001_004E': 'Estimate Total American Indian and Alaska Native alone',
         'B02001_005E': 'Estimate Total Asian alone',
         'B02001_006E': 'Estimate Total Native Hawaiian and Other Pacific Islander alone',
        #  'B02001_007E': 'Estimate Total Some other race alone',
         'B19013_001E': 'Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars)',
        #  'B14001_005E': 'Estimate Total Enrolled in school Enrolled in grade 1 to grade 4',
        #  'B14001_006E': 'Estimate Total Enrolled in school Enrolled in grade 5 to grade 8',
        #  'B14001_007E': 'Estimate Total Enrolled in school Enrolled in grade 9 to grade 12',
         'B15003_017E': 'Estimate Total Regular high school diploma',
         'B15003_022E': "Estimate Total Bachelor's degree",
         'B15003_023E': "Estimate Total Master's degree",
        #  'B01002_001E': 'Estimate Median age -- Total',
        #  'B01002_002E': 'Estimate Median age -- Male',
        #  'B01002_003E': 'Estimate Median age -- Female',
         'B09010_002E': 'Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months',
         'B11001_002E': 'Estimate Total Family households',
         }

attr_keys = list(attr.keys())
attr_values = list(attr.values())

In [ ]:
sd_list = ['28830',
 '20340',
 '35160',
 '35190',
 '11600',
 '14070',
 '02820',
 '28560',
 '09570',
 '21840',
 '35310',
 '12000',
 '28740',
 '21150',
 '29940',
 '33540',
 '32310',
 '14520',
 '16440',
 '19950',
 '21870',
 '00015',
 '04260',
 '34260',
 '34470',
 '33870']

In [ ]:
allsddata_total = pd.DataFrame(columns=attr_values)

for year in range(2015,2020):
  allsddata = pd.DataFrame(columns=attr_values)

  for schooldistrict in sd_list:
    failed = []
    try:
      data = censusdata.download('acs1', year, 
              censusdata.censusgeo([('state', '26'),
                                    ('school district (unified)', schooldistrict)]),
                                    # ('block group', '*')]),
              attr_keys, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')  #may need key to access, see report for details on how to obtain key
    except:
      failed.append(schooldistrict)
      # print(schooldistrict)
      continue
    data['GeoInformation'] = data.index
    data.reset_index(drop=True, inplace=True)
    data = data.rename(columns=attr)
    #print(data.columns)
    allsddata = allsddata.append(data)
    allsddata['Year'] = year

  allsddata['SchoolDistrict'] = allsddata['GeoInformation'].astype(str).str.split(', Michigan').str[0]
  cols = allsddata.columns.drop(['SchoolDistrict','GeoInformation'])

  allsddata[cols] = allsddata[cols].apply(pd.to_numeric, errors='coerce')
  allsddata = allsddata.reset_index()
  # allsddata_total.append(allsddata)
allsddata

,index,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,GeoInformation,Year,SchoolDistrict
0,0,60038,4770,128,749,25,48709,12520,6704,3128,6000.0,17390,"Port Huron Area School District, Michigan: Sum...",2019,Port Huron Area School District
1,0,40385,13448,152,5999,0,59064,10814,8132,2291,3707.0,16348,"Kentwood Public Schools, Michigan: Summary lev...",2019,Kentwood Public Schools
2,0,84651,10028,288,7807,0,77364,11536,21006,11406,2072.0,27647,"Walled Lake Consolidated Schools, Michigan: Su...",2019,Walled Lake Consolidated Schools
3,0,89386,9197,457,13993,0,59608,26212,12755,7013,6307.0,30480,"Warren Consolidated Schools, Michigan: Summary...",2019,Warren Consolidated Schools
4,0,87929,3904,241,1831,56,53596,12245,9875,5760,14050.0,21017,"Dearborn City School District, Michigan: Summa...",2019,Dearborn City School District
5,0,53619,16391,217,14128,0,88329,6912,20251,14621,NaN,20783,"Farmington Public School District, Michigan: S...",2019,Farmington Public School District
6,0,119679,14454,563,27241,0,77888,6817,28958,25074,1845.0,34202,"Ann Arbor Public Schools, Michigan: Summary le...",2019,Ann Arbor Public Schools
7,0,90981,6955,227,19403,0,91835,12236,25824,17418,1462.0,34002,"Plymouth-Canton Community Schools, Michigan: S...",2019,Plymouth-Canton Community Schools
8,0,85704,8937,279,2218,0,76245,17338,12337,6556,1786.0,25728,"Chippewa Valley Schools, Michigan: Summary lev...",2019,Chippewa Valley Schools
9,0,98647,6492,35,5496,0,73229,17434,20432,9517,2379.0,32148,"Livonia Public Schools, Michigan: Summary leve...",2019,Livonia Public Schools
10,0,69412,4672,324,1231,99,65828,15271,11223,4029,2810.0,19676,"Waterford School District, Michigan: Summary l...",2019,Waterford School District
11,0,98275,521857,4427,11705,25,33965,123629,42762,22326,94965.0,138731,"Detroit City School District, Michigan: Summar...",2019,Detroit City School District
12,0,32409,35994,750,4802,0,41060,14229,7208,3283,8233.0,16141,"Pontiac City School District, Michigan: Summar...",2019,Pontiac City School District
13,0,81241,26312,996,7143,0,41159,18759,15785,6581,10934.0,25180,"Lansing Public School District, Michigan: Summ...",2019,Lansing Public School District
14,0,81312,1734,68,11692,0,106854,9346,22860,13917,NaN,26994,"Rochester Community School District, Michigan:...",2019,Rochester Community School District
15,0,47593,14656,561,612,0,51398,17474,3759,694,2924.0,16066,"Taylor School District, Michigan: Summary leve...",2019,Taylor School District
16,0,20234,46300,207,1452,65,53013,12534,11408,7500,2803.0,16092,"Southfield Public School District, Michigan: S...",2019,Southfield Public School District
17,0,35870,52944,44,805,0,32236,18169,5061,2539,15449.0,24117,"Flint City School District, Michigan: Summary ...",2019,Flint City School District
18,0,129808,36367,700,3770,48,52222,24730,32357,10385,13693.0,40634,"Grand Rapids Public Schools, Michigan: Summary...",2019,Grand Rapids Public Schools
19,0,74243,24013,357,2932,0,42249,11842,13824,6811,4614.0,20493,"Kalamazoo Public School District, Michigan: Su...",2019,Kalamazoo Public School District
20,0,59726,7621,0,721,0,69474,13401,9066,3768,1550.0,18768,"L'Anse Creuse Public Schools, Michigan: Summar...",2019,L'Anse Creuse Public Schools
21,0,61084,18747,424,1196,0,52867,18146,6317,2598,6069.0,20447,"Wayne-Westland Community School District, Mich...",2019,Wayne-Westland Community School District
22,0,66652,1584,128,406,0,49668,14096,8241,2728,2995.0,17738,"Bay City School District, Michigan: Summary le...",2019,Bay City School District
23,0,42072,2188,0,20297,0,112437,4145,15473,10858,1095.0,18377,"Troy School District, Michigan: Summary level:...",2019,Troy School District
24,0,170436,6804,151,9621,16,76070,32450,28220,13706,5643.0,49903,"Utica Community Schools, Michigan: Summary lev...",2019,Utica Community Schools
25,0,81957,853,278,538,177,64872,12075,16462,5922,1945.0,22765,"Traverse City Area Public Schools, Michigan: S...",2019,Traverse City Area Public Schools

In [ ]:

allsddata2015 = pd.DataFrame(columns=attr_values)
# 2015 - 2021
# consider log median income
# limit covariates to list on google docs
# change acs 5 to acs 1
# consider averaging years for school year 
for schooldistrict in sd_list:
  failed = []
  try:
    data = censusdata.download('acs1', 2015, 
            censusdata.censusgeo([('state', '26'),
                                  ('school district (unified)', schooldistrict)]),
                                  # ('block group', '*')]),
            attr_keys, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')  #may need key to access, see report for details on how to obtain key
  except:
    failed.append(schooldistrict)
    # print(schooldistrict)
    continue
  data['GeoInformation'] = data.index
  data.reset_index(drop=True, inplace=True)
  data = data.rename(columns=attr)
  #print(data.columns)
  
  allsddata2015 = allsddata2015.append(data)

  
allsddata2015['Year'] = 2015

allsddata2015['SchoolDistrict'] = allsddata2015['GeoInformation'].astype(str).str.split(', Michigan').str[0]
cols = allsddata2015.columns.drop(['SchoolDistrict','GeoInformation'])

allsddata2015[cols] = allsddata2015[cols].apply(pd.to_numeric, errors='coerce')
allsddata2015 = allsddata2015.reset_index()
allsddata2015

,index,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,GeoInformation,Year,SchoolDistrict
0,0,61617.0,2784.0,61.0,520.0,0.0,43477,14722.0,4715.0,1590.0,5355.0,18020,"Port Huron Area School District, Michigan: Sum...",2015,Port Huron Area School District
1,0,44606.0,14081.0,186.0,3685.0,0.0,51477,8866.0,10140.0,2645.0,2138.0,16414,"Kentwood Public Schools, Michigan: Summary lev...",2015,Kentwood Public Schools
2,0,79063.0,12353.0,478.0,6234.0,0.0,70876,12483.0,20461.0,9460.0,2882.0,26037,"Walled Lake Consolidated Schools, Michigan: Su...",2015,Walled Lake Consolidated Schools
3,0,NaN,NaN,NaN,NaN,NaN,52940,23300.0,14467.0,5963.0,4857.0,30837,"Warren Consolidated Schools, Michigan: Summary...",2015,Warren Consolidated Schools
4,0,92831.0,4467.0,185.0,2585.0,231.0,51433,11407.0,10927.0,4643.0,15100.0,22176,"Dearborn City School District, Michigan: Summa...",2015,Dearborn City School District
5,0,59170.0,13800.0,51.0,10127.0,0.0,72084,8278.0,19500.0,10720.0,3086.0,22464,"Farmington Public School District, Michigan: S...",2015,Farmington Public School District
6,0,120755.0,13187.0,1044.0,26888.0,118.0,60533,7370.0,31303.0,24240.0,3728.0,33327,"Ann Arbor Public Schools, Michigan: Summary le...",2015,Ann Arbor Public Schools
7,0,91343.0,8516.0,185.0,18212.0,0.0,86928,11107.0,23311.0,14458.0,2579.0,32745,"Plymouth-Canton Community Schools, Michigan: S...",2015,Plymouth-Canton Community Schools
8,0,92214.0,9241.0,147.0,2096.0,0.0,68595,17966.0,14675.0,6921.0,2469.0,27762,"Chippewa Valley Schools, Michigan: Summary lev...",2015,Chippewa Valley Schools
9,0,99950.0,6727.0,150.0,3273.0,0.0,65736,18652.0,17340.0,7708.0,2448.0,29717,"Livonia Public Schools, Michigan: Summary leve...",2015,Livonia Public Schools
10,0,68503.0,4109.0,304.0,1402.0,0.0,59212,13236.0,10995.0,4520.0,1679.0,21018,"Waterford School District, Michigan: Summary l...",2015,Waterford School District
11,0,95272.0,538437.0,1738.0,8790.0,188.0,25984,111703.0,38959.0,17331.0,121778.0,141322,"Detroit City School District, Michigan: Summar...",2015,Detroit City School District
12,0,35025.0,35254.0,165.0,3197.0,137.0,35175,12227.0,5623.0,3781.0,10159.0,17905,"Pontiac City School District, Michigan: Summar...",2015,Pontiac City School District
13,0,73352.0,26896.0,431.0,4517.0,0.0,38057,16546.0,13212.0,4798.0,13352.0,24454,"Lansing Public School District, Michigan: Summ...",2015,Lansing Public School District
14,0,78442.0,3452.0,45.0,7936.0,0.0,91516,NaN,NaN,NaN,NaN,24733,"Rochester Community School District, Michigan:...",2015,Rochester Community School District
15,0,50259.0,9686.0,80.0,1274.0,0.0,40694,14977.0,3645.0,1274.0,6876.0,15532,"Taylor School District, Michigan: Summary leve...",2015,Taylor School District
16,0,16586.0,50162.0,71.0,894.0,0.0,51184,8101.0,10878.0,6067.0,4050.0,16006,"Southfield Public School District, Michigan: S...",2015,Southfield Public School District
17,0,40994.0,51578.0,81.0,195.0,0.0,25342,18839.0,5284.0,1529.0,17843.0,22063,"Flint City School District, Michigan: Summary ...",2015,Flint City School District
18,0,131504.0,33603.0,596.0,3987.0,149.0,41878,22076.0,27582.0,10203.0,19842.0,37788,"Grand Rapids Public Schools, Michigan: Summary...",2015,Grand Rapids Public Schools
19,0,77925.0,22433.0,450.0,3186.0,0.0,41027,9970.0,12059.0,8269.0,8984.0,22118,"Kalamazoo Public School District, Michigan: Su...",2015,Kalamazoo Public School District
20,0,60696.0,8547.0,0.0,833.0,0.0,57257,15619.0,6636.0,3074.0,3344.0,18512,"L'Anse Creuse Public Schools, Michigan: Summar...",2015,L'Anse Creuse Public Schools
21,0,60322.0,19028.0,99.0,3575.0,0.0,41042,18555.0,7379.0,2719.0,7288.0,20112,"Wayne-Westland Community School District, Mich...",2015,Wayne-Westland Community School District
22,0,65599.0,1470.0,225.0,669.0,0.0,44592,13886.0,6383.0,2549.0,4235.0,16617,"Bay City School District, Michigan: Summary le...",2015,Bay City School District
23,0,40297.0,3446.0,1067.0,18973.0,0.0,94882,5208.0,12686.0,10496.0,1522.0,18358,"Troy School District, Michigan: Summary level:...",2015,Troy School District
24,0,169908.0,5975.0,0.0,8039.0,0.0,64502,30396.0,23037.0,12590.0,7835.0,49505,"Utica Community Schools, Michigan: Summary lev...",2015,Utica Community Schools
25,0,80713.0,832.0,682.0,892.0,0.0,55538,12773.0,12861.0,4947.0,1873.0,22238,"Traverse City Area Public Schools, Michigan: S...",2015,Traverse City Area Public Schools

In [ ]:
allsddata2016 = pd.DataFrame(columns=attr_values)
## 2015 - 2021
## consider log median income
## limit covariates to list on google docs
## change acs 5 to acs 1
## consider averaging years for school year 
for schooldistrict in sd_list:
  failed = []
  try:
    data = censusdata.download('acs1', 2016, 
            censusdata.censusgeo([('state', '26'),
                                  ('school district (unified)', schooldistrict)]),
                                  # ('block group', '*')]),
            attr_keys, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')  #may need key to access, see report for details on how to obtain key
  except:
    failed.append(schooldistrict)
    # print(schooldistrict)
    continue
  data['GeoInformation'] = data.index
  data.reset_index(drop=True, inplace=True)
  data = data.rename(columns=attr)
  #print(data.columns)
  allsddata2016 = allsddata2016.append(data)
allsddata2016['Year'] = 2016

allsddata2016['SchoolDistrict'] = allsddata2016['GeoInformation'].astype(str).str.split(', Michigan').str[0]
cols = allsddata2016.columns.drop(['SchoolDistrict','GeoInformation'])

allsddata2016[cols] = allsddata2016[cols].apply(pd.to_numeric, errors='coerce')
allsddata2016 = allsddata2016.reset_index()
allsddata2016

,index,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,GeoInformation,Year,SchoolDistrict
0,0,59034.0,3193.0,205.0,1094.0,0.0,44605,13234.0,4903.0,1922.0,5543.0,16884,"Port Huron Area School District, Michigan: Sum...",2016,Port Huron Area School District
1,0,47391.0,12964.0,37.0,5716.0,0.0,53174,10664.0,8649.0,3143.0,6045.0,16587,"Kentwood Public Schools, Michigan: Summary lev...",2016,Kentwood Public Schools
2,0,84695.0,9805.0,275.0,5740.0,0.0,75317,11537.0,19915.0,10154.0,NaN,25624,"Walled Lake Consolidated Schools, Michigan: Su...",2016,Walled Lake Consolidated Schools
3,0,93571.0,10949.0,79.0,12569.0,0.0,54673,25614.0,14125.0,5003.0,9845.0,31033,"Warren Consolidated Schools, Michigan: Summary...",2016,Warren Consolidated Schools
4,0,92742.0,4268.0,176.0,1454.0,0.0,48748,11723.0,9919.0,5083.0,15680.0,22529,"Dearborn City School District, Michigan: Summa...",2016,Dearborn City School District
5,0,60964.0,16469.0,40.0,9531.0,0.0,70944,NaN,NaN,NaN,NaN,22912,"Farmington Public School District, Michigan: S...",2016,Farmington Public School District
6,0,121732.0,12749.0,820.0,27169.0,179.0,66454,7081.0,29163.0,25386.0,3114.0,35645,"Ann Arbor Public Schools, Michigan: Summary le...",2016,Ann Arbor Public Schools
7,0,96683.0,6570.0,46.0,13804.0,0.0,89706,12057.0,24754.0,16546.0,1733.0,34410,"Plymouth-Canton Community Schools, Michigan: S...",2016,Plymouth-Canton Community Schools
8,0,86002.0,11474.0,283.0,4226.0,0.0,75486,19551.0,14698.0,6725.0,NaN,28360,"Chippewa Valley Schools, Michigan: Summary lev...",2016,Chippewa Valley Schools
9,0,96776.0,6629.0,504.0,3621.0,62.0,66449,17094.0,17843.0,7484.0,2485.0,28818,"Livonia Public Schools, Michigan: Summary leve...",2016,Livonia Public Schools
10,0,67860.0,3050.0,225.0,705.0,121.0,57204,14599.0,10942.0,3264.0,2864.0,19158,"Waterford School District, Michigan: Summary l...",2016,Waterford School District
11,0,91180.0,531876.0,2173.0,12282.0,69.0,28099,109568.0,38594.0,18980.0,117580.0,139556,"Detroit City School District, Michigan: Summar...",2016,Detroit City School District
12,0,31965.0,32861.0,479.0,4289.0,111.0,34591,10977.0,6674.0,3140.0,9224.0,16023,"Pontiac City School District, Michigan: Summar...",2016,Pontiac City School District
13,0,77043.0,26600.0,704.0,5243.0,187.0,41527,18413.0,12115.0,4781.0,12864.0,24788,"Lansing Public School District, Michigan: Summ...",2016,Lansing Public School District
14,0,73333.0,5577.0,199.0,12124.0,0.0,89053,7644.0,20296.0,12372.0,1452.0,24417,"Rochester Community School District, Michigan:...",2016,Rochester Community School District
15,0,47710.0,15980.0,380.0,1328.0,0.0,44979,16553.0,3327.0,1101.0,6570.0,16803,"Taylor School District, Michigan: Summary leve...",2016,Taylor School District
16,0,15727.0,49508.0,193.0,1852.0,0.0,51126,8626.0,11122.0,7576.0,3582.0,16484,"Southfield Public School District, Michigan: S...",2016,Southfield Public School District
17,0,40448.0,51392.0,245.0,302.0,0.0,25896,17535.0,4209.0,1789.0,16760.0,22526,"Flint City School District, Michigan: Summary ...",2016,Flint City School District
18,0,125515.0,34713.0,795.0,4074.0,67.0,45207,20765.0,28570.0,9681.0,19226.0,40059,"Grand Rapids Public Schools, Michigan: Summary...",2016,Grand Rapids Public Schools
19,0,79579.0,20290.0,0.0,3421.0,0.0,42960,11139.0,11146.0,8237.0,7997.0,20355,"Kalamazoo Public School District, Michigan: Su...",2016,Kalamazoo Public School District
20,0,NaN,NaN,NaN,NaN,NaN,66791,12964.0,8129.0,3361.0,NaN,18133,"L'Anse Creuse Public Schools, Michigan: Summar...",2016,L'Anse Creuse Public Schools
21,0,58566.0,18597.0,1188.0,1921.0,81.0,45774,16898.0,7367.0,2860.0,5683.0,20325,"Wayne-Westland Community School District, Mich...",2016,Wayne-Westland Community School District
22,0,64000.0,2047.0,214.0,309.0,0.0,41056,13449.0,6147.0,2275.0,4387.0,18990,"Bay City School District, Michigan: Summary le...",2016,Bay City School District
23,0,46887.0,1898.0,149.0,17120.0,0.0,98331,5744.0,16322.0,10037.0,NaN,18709,"Troy School District, Michigan: Summary level:...",2016,Troy School District
24,0,164030.0,4118.0,337.0,7818.0,0.0,69972,31517.0,27055.0,11002.0,5203.0,49692,"Utica Community Schools, Michigan: Summary lev...",2016,Utica Community Schools
25,0,79252.0,584.0,908.0,286.0,98.0,57471,13862.0,13075.0,6115.0,3599.0,21344,"Traverse City Area Public Schools, Michigan: S...",2016,Traverse City Area Public Schools

In [ ]:
allsddata2017 = pd.DataFrame(columns=attr_values)
## 2015 - 2021
## consider log median income
## limit covariates to list on google docs
## change acs 5 to acs 1
## consider averaging years for school year 
for schooldistrict in sd_list:
  failed = []
  try:
    data = censusdata.download('acs1', 2017, 
            censusdata.censusgeo([('state', '26'),
                                  ('school district (unified)', schooldistrict)]),
                                  # ('block group', '*')]),
            attr_keys, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')  #may need key to access, see report for details on how to obtain key
  except:
    failed.append(schooldistrict)
    # print(schooldistrict)
    continue
  data['GeoInformation'] = data.index
  data.reset_index(drop=True, inplace=True)
  data = data.rename(columns=attr)
  #print(data.columns)
  allsddata2017 = allsddata2017.append(data)
allsddata2017['Year'] = 2017

allsddata2017['SchoolDistrict'] = allsddata2017['GeoInformation'].astype(str).str.split(', Michigan').str[0]
cols = allsddata2017.columns.drop(['SchoolDistrict','GeoInformation'])

allsddata2017[cols] = allsddata2017[cols].apply(pd.to_numeric, errors='coerce')
allsddata2017 = allsddata2017.reset_index()
allsddata2017

,index,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,GeoInformation,Year,SchoolDistrict
0,0,63359.0,3362.0,39.0,343.0,60.0,47461,13147.0,5184.0,2781.0,4989.0,18319,"Port Huron Area School District, Michigan: Sum...",2017,Port Huron Area School District
1,0,43125.0,12099.0,318.0,7539.0,0.0,55378,11793.0,9554.0,4313.0,3634.0,16576,"Kentwood Public Schools, Michigan: Summary lev...",2017,Kentwood Public Schools
2,0,88518.0,10685.0,124.0,6090.0,0.0,75278,11992.0,21814.0,10039.0,3468.0,28722,"Walled Lake Consolidated Schools, Michigan: Su...",2017,Walled Lake Consolidated Schools
3,0,92536.0,8485.0,94.0,12908.0,0.0,55653,20648.0,16263.0,6200.0,9075.0,30982,"Warren Consolidated Schools, Michigan: Summary...",2017,Warren Consolidated Schools
4,0,90717.0,4627.0,40.0,1938.0,0.0,45487,12732.0,10808.0,4795.0,14947.0,22444,"Dearborn City School District, Michigan: Summa...",2017,Dearborn City School District
5,0,52375.0,13534.0,166.0,14698.0,30.0,82035,7557.0,18197.0,12888.0,NaN,23220,"Farmington Public School District, Michigan: S...",2017,Farmington Public School District
6,0,120789.0,11739.0,482.0,30303.0,105.0,75568,7506.0,29540.0,27317.0,1584.0,33181,"Ann Arbor Public Schools, Michigan: Summary le...",2017,Ann Arbor Public Schools
7,0,90994.0,9007.0,114.0,18101.0,0.0,87379,14346.0,24657.0,16153.0,2026.0,31944,"Plymouth-Canton Community Schools, Michigan: S...",2017,Plymouth-Canton Community Schools
8,0,94834.0,9304.0,881.0,2970.0,0.0,68735,18506.0,14945.0,4533.0,NaN,27897,"Chippewa Valley Schools, Michigan: Summary lev...",2017,Chippewa Valley Schools
9,0,95227.0,10414.0,224.0,3474.0,0.0,72588,15882.0,19823.0,7936.0,1517.0,30957,"Livonia Public Schools, Michigan: Summary leve...",2017,Livonia Public Schools
10,0,68217.0,4838.0,963.0,1424.0,0.0,59522,13836.0,10382.0,4009.0,3924.0,20144,"Waterford School District, Michigan: Summary l...",2017,Waterford School District
11,0,97402.0,532057.0,2656.0,11938.0,134.0,30344,115888.0,36605.0,21074.0,108460.0,141283,"Detroit City School District, Michigan: Summar...",2017,Detroit City School District
12,0,41590.0,28313.0,227.0,2141.0,0.0,40634,13330.0,5564.0,3192.0,8934.0,16069,"Pontiac City School District, Michigan: Summar...",2017,Pontiac City School District
13,0,77266.0,27661.0,716.0,6313.0,0.0,40144,18598.0,12453.0,6446.0,15061.0,25933,"Lansing Public School District, Michigan: Summ...",2017,Lansing Public School District
14,0,78556.0,3121.0,561.0,7829.0,0.0,101352,7946.0,20188.0,15977.0,894.0,27156,"Rochester Community School District, Michigan:...",2017,Rochester Community School District
15,0,47246.0,14256.0,382.0,1054.0,0.0,45455,15146.0,4598.0,1134.0,7952.0,16318,"Taylor School District, Michigan: Summary leve...",2017,Taylor School District
16,0,14064.0,51362.0,87.0,1513.0,0.0,60524,8516.0,11544.0,8469.0,1709.0,15981,"Southfield Public School District, Michigan: S...",2017,Southfield Public School District
17,0,36777.0,51514.0,790.0,1229.0,0.0,26880,17679.0,5601.0,2133.0,13857.0,22823,"Flint City School District, Michigan: Summary ...",2017,Flint City School District
18,0,128663.0,38047.0,491.0,4797.0,0.0,48239,23017.0,29863.0,11437.0,15854.0,40444,"Grand Rapids Public Schools, Michigan: Summary...",2017,Grand Rapids Public Schools
19,0,77956.0,20314.0,355.0,2158.0,0.0,41932,10752.0,13814.0,7395.0,8092.0,20452,"Kalamazoo Public School District, Michigan: Su...",2017,Kalamazoo Public School District
20,0,NaN,NaN,NaN,NaN,NaN,66742,NaN,NaN,NaN,NaN,19026,"L'Anse Creuse Public Schools, Michigan: Summar...",2017,L'Anse Creuse Public Schools
21,0,61753.0,15512.0,540.0,3124.0,0.0,49295,18203.0,7321.0,2528.0,5227.0,21482,"Wayne-Westland Community School District, Mich...",2017,Wayne-Westland Community School District
22,0,64797.0,1883.0,448.0,454.0,0.0,45110,13317.0,7152.0,3378.0,3222.0,17780,"Bay City School District, Michigan: Summary le...",2017,Bay City School District
23,0,43495.0,2902.0,375.0,17978.0,0.0,99263,NaN,NaN,NaN,NaN,18806,"Troy School District, Michigan: Summary level:...",2017,Troy School District
24,0,161617.0,7185.0,463.0,9652.0,0.0,77507,30156.0,27690.0,12106.0,3277.0,52181,"Utica Community Schools, Michigan: Summary lev...",2017,Utica Community Schools
25,0,79456.0,584.0,286.0,341.0,178.0,59627,NaN,NaN,NaN,3406.0,23392,"Traverse City Area Public Schools, Michigan: S...",2017,Traverse City Area Public Schools

In [ ]:
allsddata2018 = pd.DataFrame(columns=attr_values)
## 2015 - 2021
## consider log median income
## limit covariates to list on google docs
## change acs 5 to acs 1
## consider averaging years for school year 
for schooldistrict in sd_list:
  failed = []
  try:
    data = censusdata.download('acs1', 2018, 
            censusdata.censusgeo([('state', '26'),
                                  ('school district (unified)', schooldistrict)]),
                                  # ('block group', '*')]),
            attr_keys, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')  #may need key to access, see report for details on how to obtain key
  except:
    failed.append(schooldistrict)
    # print(schooldistrict)
    continue
  data['GeoInformation'] = data.index
  data.reset_index(drop=True, inplace=True)
  data = data.rename(columns=attr)
  #print(data.columns)
  allsddata2018 = allsddata2018.append(data)
allsddata2018['Year'] = 2018

allsddata2018['SchoolDistrict'] = allsddata2018['GeoInformation'].astype(str).str.split(', Michigan').str[0]
cols = allsddata2018.columns.drop(['SchoolDistrict','GeoInformation'])

allsddata2018[cols] = allsddata2018[cols].apply(pd.to_numeric, errors='coerce')
allsddata2018 = allsddata2018.reset_index()
allsddata2018

,index,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,GeoInformation,Year,SchoolDistrict
0,0,61326.0,3765.0,158.0,315.0,57.0,45829,14134,4852,2918,5394.0,17924,"Port Huron Area School District, Michigan: Sum...",2018,Port Huron Area School District
1,0,42190.0,16680.0,127.0,5907.0,166.0,53939,10884,11023,2760,NaN,16658,"Kentwood Public Schools, Michigan: Summary lev...",2018,Kentwood Public Schools
2,0,82950.0,7483.0,211.0,11694.0,0.0,75854,12117,23701,10273,1310.0,26068,"Walled Lake Consolidated Schools, Michigan: Su...",2018,Walled Lake Consolidated Schools
3,0,92497.0,11214.0,571.0,9808.0,0.0,61732,20785,15613,5659,7522.0,29380,"Warren Consolidated Schools, Michigan: Summary...",2018,Warren Consolidated Schools
4,0,92917.0,2807.0,530.0,3098.0,0.0,55156,12710,12435,6519,13415.0,23243,"Dearborn City School District, Michigan: Summa...",2018,Dearborn City School District
5,0,53518.0,14574.0,470.0,12591.0,171.0,87015,8806,19955,12204,NaN,21188,"Farmington Public School District, Michigan: S...",2018,Farmington Public School District
6,0,122124.0,11125.0,152.0,31813.0,92.0,72694,6783,29496,26961,2341.0,34173,"Ann Arbor Public Schools, Michigan: Summary le...",2018,Ann Arbor Public Schools
7,0,95261.0,7512.0,519.0,16106.0,0.0,91148,11730,27718,16059,2811.0,33289,"Plymouth-Canton Community Schools, Michigan: S...",2018,Plymouth-Canton Community Schools
8,0,90349.0,16257.0,709.0,2903.0,0.0,75895,18487,14601,6784,4376.0,29807,"Chippewa Valley Schools, Michigan: Summary lev...",2018,Chippewa Valley Schools
9,0,97318.0,6186.0,58.0,4692.0,0.0,72101,16268,19625,8054,2327.0,28582,"Livonia Public Schools, Michigan: Summary leve...",2018,Livonia Public Schools
10,0,67600.0,6544.0,358.0,1100.0,0.0,59357,14259,11343,4632,2647.0,20397,"Waterford School District, Michigan: Summary l...",2018,Waterford School District
11,0,103779.0,522296.0,1770.0,10597.0,184.0,31289,113188,38945,21568,107756.0,137782,"Detroit City School District, Michigan: Summar...",2018,Detroit City School District
12,0,37048.0,34114.0,219.0,4769.0,0.0,36092,11963,8478,3191,8538.0,15570,"Pontiac City School District, Michigan: Summar...",2018,Pontiac City School District
13,0,78014.0,27044.0,519.0,4799.0,0.0,40374,16489,13997,5494,11946.0,27414,"Lansing Public School District, Michigan: Summ...",2018,Lansing Public School District
14,0,77560.0,2527.0,98.0,10846.0,0.0,103842,8486,21082,14585,NaN,25231,"Rochester Community School District, Michigan:...",2018,Rochester Community School District
15,0,NaN,NaN,NaN,NaN,NaN,51595,16535,4531,908,5153.0,17525,"Taylor School District, Michigan: Summary leve...",2018,Taylor School District
16,0,16863.0,49761.0,43.0,1608.0,0.0,55503,7528,9739,7565,NaN,16667,"Southfield Public School District, Michigan: S...",2018,Southfield Public School District
17,0,37069.0,51902.0,378.0,157.0,66.0,28844,18662,4875,2077,16281.0,21155,"Flint City School District, Michigan: Summary ...",2018,Flint City School District
18,0,130784.0,34948.0,1063.0,1930.0,204.0,51807,23410,31532,11673,13354.0,41384,"Grand Rapids Public Schools, Michigan: Summary...",2018,Grand Rapids Public Schools
19,0,78935.0,21188.0,368.0,2337.0,112.0,43736,10725,14693,7096,9407.0,20293,"Kalamazoo Public School District, Michigan: Su...",2018,Kalamazoo Public School District
20,0,NaN,NaN,NaN,NaN,NaN,67696,12382,8014,2837,3392.0,19022,"L'Anse Creuse Public Schools, Michigan: Summar...",2018,L'Anse Creuse Public Schools
21,0,59079.0,22725.0,205.0,2914.0,0.0,48326,17402,8171,4047,8061.0,20576,"Wayne-Westland Community School District, Mich...",2018,Wayne-Westland Community School District
22,0,NaN,NaN,NaN,NaN,NaN,49002,16756,6986,2257,3587.0,18751,"Bay City School District, Michigan: Summary le...",2018,Bay City School District
23,0,42110.0,3525.0,20.0,19280.0,44.0,101401,6144,14460,9982,NaN,18238,"Troy School District, Michigan: Summary level:...",2018,Troy School District
24,0,168211.0,4347.0,174.0,10938.0,217.0,72652,31004,25364,12997,4969.0,51143,"Utica Community Schools, Michigan: Summary lev...",2018,Utica Community Schools
25,0,82079.0,672.0,790.0,562.0,118.0,65465,13621,15089,5987,2563.0,21296,"Traverse City Area Public Schools, Michigan: S...",2018,Traverse City Area Public Schools

In [ ]:
allsddata2019 = pd.DataFrame(columns=attr_values)
## 2015 - 2021
## consider log median income
## limit covariates to list on google docs
## change acs 5 to acs 1
## consider averaging years for school year 
for schooldistrict in sd_list:
  failed = []
  try:
    data = censusdata.download('acs1', 2019, 
            censusdata.censusgeo([('state', '26'),
                                  ('school district (unified)', schooldistrict)]),
                                  # ('block group', '*')]),
            attr_keys, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')  #may need key to access, see report for details on how to obtain key
  except:
    failed.append(schooldistrict)
    # print(schooldistrict)
    continue
  data['GeoInformation'] = data.index
  data.reset_index(drop=True, inplace=True)
  data = data.rename(columns=attr)
  #print(data.columns)
  allsddata2019 = allsddata2019.append(data)
allsddata2019['Year'] = 2019

allsddata2019['SchoolDistrict'] = allsddata2019['GeoInformation'].astype(str).str.split(', Michigan').str[0]
cols = allsddata2019.columns.drop(['SchoolDistrict','GeoInformation'])

allsddata2019[cols] = allsddata2019[cols].apply(pd.to_numeric, errors='coerce')
allsddata2019 = allsddata2019.reset_index()
allsddata2019

,index,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,GeoInformation,Year,SchoolDistrict
0,0,60038,4770,128,749,25,48709,12520,6704,3128,6000.0,17390,"Port Huron Area School District, Michigan: Sum...",2019,Port Huron Area School District
1,0,40385,13448,152,5999,0,59064,10814,8132,2291,3707.0,16348,"Kentwood Public Schools, Michigan: Summary lev...",2019,Kentwood Public Schools
2,0,84651,10028,288,7807,0,77364,11536,21006,11406,2072.0,27647,"Walled Lake Consolidated Schools, Michigan: Su...",2019,Walled Lake Consolidated Schools
3,0,89386,9197,457,13993,0,59608,26212,12755,7013,6307.0,30480,"Warren Consolidated Schools, Michigan: Summary...",2019,Warren Consolidated Schools
4,0,87929,3904,241,1831,56,53596,12245,9875,5760,14050.0,21017,"Dearborn City School District, Michigan: Summa...",2019,Dearborn City School District
5,0,53619,16391,217,14128,0,88329,6912,20251,14621,NaN,20783,"Farmington Public School District, Michigan: S...",2019,Farmington Public School District
6,0,119679,14454,563,27241,0,77888,6817,28958,25074,1845.0,34202,"Ann Arbor Public Schools, Michigan: Summary le...",2019,Ann Arbor Public Schools
7,0,90981,6955,227,19403,0,91835,12236,25824,17418,1462.0,34002,"Plymouth-Canton Community Schools, Michigan: S...",2019,Plymouth-Canton Community Schools
8,0,85704,8937,279,2218,0,76245,17338,12337,6556,1786.0,25728,"Chippewa Valley Schools, Michigan: Summary lev...",2019,Chippewa Valley Schools
9,0,98647,6492,35,5496,0,73229,17434,20432,9517,2379.0,32148,"Livonia Public Schools, Michigan: Summary leve...",2019,Livonia Public Schools
10,0,69412,4672,324,1231,99,65828,15271,11223,4029,2810.0,19676,"Waterford School District, Michigan: Summary l...",2019,Waterford School District
11,0,98275,521857,4427,11705,25,33965,123629,42762,22326,94965.0,138731,"Detroit City School District, Michigan: Summar...",2019,Detroit City School District
12,0,32409,35994,750,4802,0,41060,14229,7208,3283,8233.0,16141,"Pontiac City School District, Michigan: Summar...",2019,Pontiac City School District
13,0,81241,26312,996,7143,0,41159,18759,15785,6581,10934.0,25180,"Lansing Public School District, Michigan: Summ...",2019,Lansing Public School District
14,0,81312,1734,68,11692,0,106854,9346,22860,13917,NaN,26994,"Rochester Community School District, Michigan:...",2019,Rochester Community School District
15,0,47593,14656,561,612,0,51398,17474,3759,694,2924.0,16066,"Taylor School District, Michigan: Summary leve...",2019,Taylor School District
16,0,20234,46300,207,1452,65,53013,12534,11408,7500,2803.0,16092,"Southfield Public School District, Michigan: S...",2019,Southfield Public School District
17,0,35870,52944,44,805,0,32236,18169,5061,2539,15449.0,24117,"Flint City School District, Michigan: Summary ...",2019,Flint City School District
18,0,129808,36367,700,3770,48,52222,24730,32357,10385,13693.0,40634,"Grand Rapids Public Schools, Michigan: Summary...",2019,Grand Rapids Public Schools
19,0,74243,24013,357,2932,0,42249,11842,13824,6811,4614.0,20493,"Kalamazoo Public School District, Michigan: Su...",2019,Kalamazoo Public School District
20,0,59726,7621,0,721,0,69474,13401,9066,3768,1550.0,18768,"L'Anse Creuse Public Schools, Michigan: Summar...",2019,L'Anse Creuse Public Schools
21,0,61084,18747,424,1196,0,52867,18146,6317,2598,6069.0,20447,"Wayne-Westland Community School District, Mich...",2019,Wayne-Westland Community School District
22,0,66652,1584,128,406,0,49668,14096,8241,2728,2995.0,17738,"Bay City School District, Michigan: Summary le...",2019,Bay City School District
23,0,42072,2188,0,20297,0,112437,4145,15473,10858,1095.0,18377,"Troy School District, Michigan: Summary level:...",2019,Troy School District
24,0,170436,6804,151,9621,16,76070,32450,28220,13706,5643.0,49903,"Utica Community Schools, Michigan: Summary lev...",2019,Utica Community Schools
25,0,81957,853,278,538,177,64872,12075,16462,5922,1945.0,22765,"Traverse City Area Public Schools, Michigan: S...",2019,Traverse City Area Public Schools

In [ ]:
allsddata = pd.concat([allsddata2015, allsddata2016, allsddata2017, allsddata2018, allsddata2019], ignore_index=True)

pd.options.display.max_columns = 50
scott_data_reduced = allsddata
scott_data_reduced.drop(columns=['GeoInformation', 'index'], inplace = True)

In [ ]:
scott_data_reduced = scott_data_reduced.set_index('SchoolDistrict')
scott_data_reduced

,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,Year
SchoolDistrict,,,,,,,,,,,,
Port Huron Area School District,61617.0,2784.0,61.0,520.0,0.0,43477,14722.0,4715.0,1590.0,5355.0,18020,2015
Kentwood Public Schools,44606.0,14081.0,186.0,3685.0,0.0,51477,8866.0,10140.0,2645.0,2138.0,16414,2015
Walled Lake Consolidated Schools,79063.0,12353.0,478.0,6234.0,0.0,70876,12483.0,20461.0,9460.0,2882.0,26037,2015
Warren Consolidated Schools,NaN,NaN,NaN,NaN,NaN,52940,23300.0,14467.0,5963.0,4857.0,30837,2015
Dearborn City School District,92831.0,4467.0,185.0,2585.0,231.0,51433,11407.0,10927.0,4643.0,15100.0,22176,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
Wayne-Westland Community School District,61084.0,18747.0,424.0,1196.0,0.0,52867,18146.0,6317.0,2598.0,6069.0,20447,2019
Bay City School District,66652.0,1584.0,128.0,406.0,0.0,49668,14096.0,8241.0,2728.0,2995.0,17738,2019
Troy School District,42072.0,2188.0,0.0,20297.0,0.0,112437,4145.0,15473.0,10858.0,1095.0,18377,2019
Utica Community Schools,170436.0,6804.0,151.0,9621.0,16.0,76070,32450.0,28220.0,13706.0,5643.0,49903,2019
Traverse City Area Public Schools,81957.0,853.0,278.0,538.0,177.0,64872,12075.0,16462.0,5922.0,1945.0,22765,2019

In [ ]:
allsddata = pd.DataFrame(columns=attr_values)

for schooldistrict in sd_nums:
  failed = []
  try:
    data = censusdata.download('acs5', 2020, 
            censusdata.censusgeo([('state', '26'),
                                  ('school district (unified)', schooldistrict)]),
                                  # ('block group', '*')]),
            attr_keys, key='b15ade4ca040c6435803ef83605eccaa17abb8e0')  #may need key to access, see report for details on how to obtain key
  except:
    failed.append(schooldistrict)
    # print(schooldistrict)
    continue
  data['GeoInformation'] = data.index
  data.reset_index(drop=True, inplace=True)
  data = data.rename(columns=attr)
  #print(data.columns)
  allsddata = allsddata.append(data)

allsddata['SchoolDistrict'] = allsddata['GeoInformation'].astype(str).str.split(', Michigan').str[0]
cols = allsddata.columns.drop(['SchoolDistrict','GeoInformation'])

allsddata[cols] = allsddata[cols].apply(pd.to_numeric, errors='coerce')
allsddata = allsddata.reset_index()
allsddata

,index,Estimate Total White alone,Estimate Total Black or African American alone,Estimate Total American Indian and Alaska Native alone,Estimate Total Asian alone,Estimate Total Native Hawaiian and Other Pacific Islander alone,Estimate Median household income in the past 12 months (in 2018 inflation-adjusted dollars),Estimate Total Regular high school diploma,Estimate Total Bachelor's degree,Estimate Total Master's degree,"Estimate Total Living in household with Supplemental Security Income (SSI), cash public assistance income, or Food Stamps/SNAP in the past 12 months",Estimate Total Family households,GeoInformation,SchoolDistrict
0,0,3942,42,329,17,0,45000,1273,367,137,278,1251,"L'Anse Area Schools, Michigan: Summary level: ...",L'Anse Area Schools
1,0,1968,4,9,43,0,51453,670,224,66,96,518,"Superior Central Schools, Michigan: Summary le...",Superior Central Schools
2,0,2968,10,0,91,0,53716,454,228,166,272,695,"Adams Township School District, Michigan: Summ...",Adams Township School District
3,0,7960,0,19,6,0,67762,1733,1580,663,138,2527,"Addison Community Schools, Michigan: Summary l...",Addison Community Schools
4,0,27048,895,99,74,10,48250,6317,2474,1551,1632,6881,"Adrian City School District, Michigan: Summary...",Adrian City School District
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,0,26379,1830,106,826,0,59597,6853,3091,1234,1249,7671,"Southgate Community School District, Michigan:...",Southgate Community School District
510,0,13954,69,30,259,0,73054,3190,1563,826,427,3976,"Sparta Area Schools, Michigan: Summary level: ...",Sparta Area Schools
511,0,12133,18,54,76,0,81333,1605,2630,1037,62,3635,"Spring Lake Public Schools, Michigan: Summary ...",Spring Lake Public Schools
512,0,5111,95,82,8,0,61667,1299,354,135,256,1435,"Springport Public Schools, Michigan: Summary l...",Springport Public Schools
513,0,5767,44,19,12,0,60357,1486,442,191,379,1813,"St. Charles Community Schools, Michigan: Summa...",St. Charles Community Schools

In [ ]:
allsddata.drop(columns=['GeoInformation', 'index'], inplace = True)
scott_data = allsddata.set_index('SchoolDistrict')

In [ ]:
from google.colab import  drive
drive.mount('/drive')
scott_data.to_csv('/drive/My Drive/SIADS_697_698_Capstone/4_Colabs/3_Data_Final/Demographic_Data.csv')

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).

END OF CAPSTONE CODE FOR DEMOGRAPHIC DATA